import type { Metadata } from "next";
import "./globals.css";
import ConvexClientProvider from "./convex-client-provider";

import { Inter } from "next/font/google"
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased ${inter.className}`}
        >
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          <ConvexClientProvider>

            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
